model:
  d_model : 512
  N : 6
  h : 8
  dropout : 0.01
  d_ff : 2048
  seq_len: 256

data:
  train_batch_size: 10
  val_batch_size: 10
  max_length : 256
  stride : 256

training:
  train_or_load : 'train' # train to train, load to load
  model_saved_at : 'saved_models/dec_model_ep50_bs100_mxln20.pth'
  load_from_checkpoint : False
  checkpoint: "saved_checkpoints/dec_checkpoint.pth.tar"
  num_epochs: 50  
  lr : 0.0001 
  eps: 1.0e-9

train_test_split:
  ratio : 0.9